version: "3.2"
services:
  php:
    build: './env/php/'
    networks:
      - frontend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './env/apache/'
    depends_on:
      - mysql
    networks:
	  - frontend
	  - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=piotr
      - MYSQL_PASSWORD=qwerty123
networks:
  frontend:
  backend:
